config/routes.rb
Rails.application.routes.draw do
  resources :post_attaches
  # For details on the DSLq available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get   '/signup', to: 'users#new'
  post  '/signup', to: 'users#create'

  get   '/signin', to: 'sessions#new'
  post  '/signin', to: 'sessions#create'

  get   '/allpost', to: 'posts#index2'
  post  '/allpost', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  # get '/search' => 'posts#search', :as => 'search_page'
  # get '/searchbypost' => 'posts#searchbypost', :as => 'searchbypost_page'
 
  # get '/search', to: 'posts#search'
  get '/searchbypost', to: 'posts#searchbypost'
  

  # except は only の逆で、指定したアクション以外の全てのアクションに適用する
  resources :users, except: [:new, :create]
  resources :posts, except: [:index]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  resources :posts
  get '/upload_photos' => 'photos#upload_photos', as: :upload_photos
  post '/upload' => 'photos#upload', as: :upload
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :posts
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :posts
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :posts
end

app/models/major.rb
class Major < ApplicationRecord
has_many :posts
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :country
  belongs_to :language
  belongs_to :stay_type
  belongs_to :kind
  belongs_to :term
  belongs_to :budget
  belongs_to :major

  validates :title, presence: true, length: { maximum: 20 }
  validates :school, presence: true
  validates :school_address, presence: true
  validates :comment_social, presence: true
  validates :comment_country, presence: true
  validates :comment_advice, presence: true
  validates :comment_school, presence: true
  mount_uploader :image, PostImageUploader
  mount_uploaders :avatars, AvatarUploader
  has_many :avatars
  accepts_nested_attributes_for :avatars
  has_many :post_attaches
   accepts_nested_attributes_for :post_attaches
  # def self.search(search)
  #   where("name LIKE ? OR country LIKE ?", "%#{search}%", "%#{search}%") 
  # end
end

app/models/post_attach.rb
class PostAttach < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sex.rb
class Sex < ApplicationRecord
    has_many :users
end

app/models/stay.rb
class Stay < ApplicationRecord
has_many :posts
end

app/models/stay_type.rb
class StayType < ApplicationRecord
  has_many :posts
end

app/models/term.rb
class Term < ApplicationRecord
has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  # userを削除したらそのuserに属するpostも削除される
  has_many :posts, dependent: :destroy

  # DM機能関係
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  # saveする前に、入力されたemailを全て小文字に変換する
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 20 }

  # 入力されたものがemailとしてふさわしいかどうかを検証する正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }}

  has_secure_password
  # users#edit でパスワードの入力を必要としないための記述
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # carrierwaveのuploaderとuser.imageを結びつけるための記述
  mount_uploader :image, UserImageUploader
  acts_as_messageable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in?, only: :show

  def index
    @users = User.all.order(id: :asc)
  end
  
  def show
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      # もし開いているページがcurrent_userのページなら何もしない
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to signup_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :name, 
        :email, 
        :password, 
        :password_confirmation, 
        :gender_id, 
        :image
      )
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="signupform">
  <%= form_with model: @user, url: url, local: true do |f| %>
    <%# エラーメッセージを表示 %>
    <%= render 'shared/error_messages', model: f.object %>

    <!--<div class="name">
        <label for="name"><%= f.label :name %></label><br>
        <div class="name_field"> 
          <%= f.text_field :name %>
        </div>
    </div>-->

    <div class="signupform-name">
      <label for="name"><%= f.label :name %></label><br>
      <div class="signupform-name_field">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="signupform-email">
      <label for="email"><%= f.label :email %></label><br>
      <div class="email_field">
        <%= f.email_field :email %>
      </div>
    </div>

    <!--<div>
      <h4>
        <%= f.label :email %>: 
        <%= f.email_field :email %>
      </h4>
    </div>-->

    <div class="signupform-gender">
        <label for="gender"><%= f.label :gender %></label><br>
        <div class="gender_select"> 
          <%= f.collection_select :gender_id, Gender.all, :id, :name, prompt: "Not selected" %>
        </div>
    </div>

    <!--<div class="label-box__inner">
      <label for="image"><%= f.label :image %></label><br>
      <div class="image_field">
        <%= f.file_field :image, class: "input-default" %>
        <div class="boxFileSelect"></div>
      </div>
    </div>-->

    <div class="signupform-image">
      <label for="image" class="image_input">Image</label>
      <div class="image_field">
        <%= f.label :image %>
        <%= f.file_field :image, class: "input_default" %>
      </div>
    </div>

    <div class="signupform-password">
        <label for="password"><%= f.label :password %></label><br>
        <div class="password_field">
          <%= f.password_field :password %>
        </div>
    </div>

    <div class="signupform-confirmation">
        <label for="confirmation"><%= f.label :password_confirmation, "Confirmation" %></label><br>
        <div class="confirmation_field"> 
          <%= f.password_field :password_confirmation %>
        </div>
    </div>

    <hr class="signupform-style">

    <div class="signupform-button">
      <!--<%= f.submit yield(:button_text) %>-->
      <%= f.submit 'Create my account', :class=>"btn" %>
    </div>

  <% end %>
  <%= link_to  "Back", :back, class: "back" %>

</div>

app/views/users/edit.html.erb
<div class="ed">
    <div class="ed-title">
        Edit User
    </div>
    <% provide(:button_text, 'Update') %>
    <%= render 'form', url: @user %>
</div>

app/views/users/index.html.erb
<p class = "chattitle">Let's chat!</p>
<% @users.each do |user| %>
  <div class = "chatallusers">
    <%= link_to user_path(user) do %>
      <%= image_tag user.image.url, size: '160x160' %>
      <div class = "chatusername">
        <a>
          <%= user.name %>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="signupform">
    <div class="signupform-title">
        Sign up
    </div>
    <% provide(:button_text, 'Create my account') %>
    <%= render "form", url: signup_path %>
    <!--<p class="ifmessage">
        If you have already signed up,
    </p>-->
    <!--<%= link_to  "Sign in", signin_path, class: "ifsignin" %>-->

    <!--<%= link_to  "Back", :back, class: "back" %>-->

</div>

app/views/users/show.html.erb
<div class = "mypagedetail">
  <p class = "mypagetitle">Mypage</p>
  <div class = "mypageimage">
    <%= image_tag @user.image.url %>
  </div>
  <div class = "mypagecontents">
    <p class = "mypagename"><%= @user.name %></p>
    <p class = "mypageeg">E-mail: <%= @user.email %></p>
    <p class = "mypageeg">Gender: <%= @user.gender.name %></p>
  </div>
  
  <div class = "mypagebuttonaaa">
    <a><%= link_to  "Delete", @current_user, method: :delete, data: { confirm: "Are You Sure?" } %></a>
    <a><%= link_to  "Edit", edit_user_path(@current_user) %></a>
  </div>
</div>
<!--
<%
=begin%>
 <%= link_to "My Post", root_url(@current_user) %> 
<%
=end%>
-->
<div class = "mypagebutton">
  <% if current_user.id == @user.id %>
    <a class = "mypagebuttondetail">
      <a><%= link_to  "New post", new_post_path %></a>
      <a><%= link_to  "Sign out", signout_path, method: :delete %></a>
      <a><%= link_to "Go Chat", "/users"%></a>
      <a><%= link_to  "Back", :back %>
    </a>
  <% else %>
    <% if @isRoom == true %>
      <%= link_to "Go Chat", "/rooms/#{@roomId}" %>
    <% else %>
      <%= form_with model: @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "Start Chat" %>
      <% end %>
    <% end %> 
  <% end %>

    <!--<%= link_to  "Back", :back %>-->

</div>