config/routes.rb
Rails.application.routes.draw do
  resources :post_attaches
  # For details on the DSLq available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get   '/signup', to: 'users#new'
  post  '/signup', to: 'users#create'

  get   '/signin', to: 'sessions#new'
  post  '/signin', to: 'sessions#create'

  get   '/allpost', to: 'posts#index2'
  post  '/allpost', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  # get '/search' => 'posts#search', :as => 'search_page'
  # get '/searchbypost' => 'posts#searchbypost', :as => 'searchbypost_page'
 
  # get '/search', to: 'posts#search'
  get '/searchbypost', to: 'posts#searchbypost'
  

  # except は only の逆で、指定したアクション以外の全てのアクションに適用する
  resources :users, except: [:new, :create]
  resources :posts, except: [:index]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  resources :posts
  get '/upload_photos' => 'photos#upload_photos', as: :upload_photos
  post '/upload' => 'photos#upload', as: :upload
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :posts
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :posts
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :posts
end

app/models/major.rb
class Major < ApplicationRecord
has_many :posts
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :country
  belongs_to :language
  belongs_to :stay_type
  belongs_to :kind
  belongs_to :term
  belongs_to :budget
  belongs_to :major

  validates :title, presence: true, length: { maximum: 20 }
  validates :school, presence: true
  validates :school_address, presence: true
  validates :comment_social, presence: true
  validates :comment_country, presence: true
  validates :comment_advice, presence: true
  validates :comment_school, presence: true
  mount_uploader :image, PostImageUploader
  mount_uploaders :avatars, AvatarUploader
  has_many :avatars
  accepts_nested_attributes_for :avatars
  has_many :post_attaches
   accepts_nested_attributes_for :post_attaches
  # def self.search(search)
  #   where("name LIKE ? OR country LIKE ?", "%#{search}%", "%#{search}%") 
  # end
end

app/models/post_attach.rb
class PostAttach < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sex.rb
class Sex < ApplicationRecord
    has_many :users
end

app/models/stay.rb
class Stay < ApplicationRecord
has_many :posts
end

app/models/stay_type.rb
class StayType < ApplicationRecord
  has_many :posts
end

app/models/term.rb
class Term < ApplicationRecord
has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  # userを削除したらそのuserに属するpostも削除される
  has_many :posts, dependent: :destroy

  # DM機能関係
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  # saveする前に、入力されたemailを全て小文字に変換する
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 20 }

  # 入力されたものがemailとしてふさわしいかどうかを検証する正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }}

  has_secure_password
  # users#edit でパスワードの入力を必要としないための記述
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # carrierwaveのuploaderとuser.imageを結びつけるための記述
  mount_uploader :image, UserImageUploader
  acts_as_messageable
end

app/controllers/post_attaches_controller.rb
class PostAttachesController < ApplicationController
  before_action :set_post_attach, only: [:show, :edit, :update, :destroy]

  # GET /post_attaches
  # GET /post_attaches.json
  def index
    @post_attaches = PostAttach.all
  end

  # GET /post_attaches/1
  # GET /post_attaches/1.json
  def show
  end

  # GET /post_attaches/new
  def new
    @post_attach = PostAttach.new
  end

  # GET /post_attaches/1/edit
  def edit
  end

  # POST /post_attaches
  # POST /post_attaches.json
  def create
    @post_attach = PostAttach.new(post_attach_params)

    respond_to do |format|
      if @post_attach.save
        format.html { redirect_to @post_attach, notice: 'Post attach was successfully created.' }
        format.json { render :show, status: :created, location: @post_attach }
      else
        format.html { render :new }
        format.json { render json: @post_attach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attaches/1
  # PATCH/PUT /post_attaches/1.json
  # def update
  #   respond_to do |format|
  #     if @post_attach.update(post_attach_params)
  #       format.html { redirect_to @post_attach, notice: 'Post attach was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post_attach }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post_attach.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def update
    respond_to do |format|
      if @post_attach.update(post_attach_params)
        format.html { redirect_to @post_attach.post, notice: 'Post attachment was successfully updated.' }
      end 
    end
  end 

  # DELETE /post_attaches/1
  # DELETE /post_attaches/1.json
  def destroy
    @post_attach.destroy
    respond_to do |format|
      format.html { redirect_to post_attaches_url, notice: 'Post attach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attach
      @post_attach = PostAttach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attach_params
      params.require(:post_attach).permit(:post_id, :avatar)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_attaches_helper.rb
module PostAttachesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/post_attaches/_form.html.erb
<%= form_with(model: post_attach, local: true) do |form| %>
  <% if post_attach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_attach.errors.count, "error") %> prohibited this post_attach from being saved:</h2>

      <ul>
      <% post_attach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_attaches/edit.html.erb
<h1>Editing Post Attach</h1>

<%= render 'form', post_attach: @post_attach %>

<%= link_to 'Show', @post_attach %> |
<%= link_to 'Back', post_attaches_path %>

app/views/post_attaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Attaches</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attaches.each do |post_attach| %>
      <tr>
        <td><%= post_attach.post_id %></td>
        <td><%= post_attach.avatar %></td>
        <td><%= link_to 'Show', post_attach %></td>
        <td><%= link_to 'Edit', edit_post_attach_path(post_attach) %></td>
        <td><%= link_to 'Destroy', post_attach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Attach', new_post_attach_path %>

app/views/post_attaches/new.html.erb
<h1>New Post Attach</h1>

<%= render 'form', post_attach: @post_attach %>

<%= link_to 'Back', post_attaches_path %>

app/views/post_attaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attach.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attach.avatar %>
</p>

<%= link_to 'Edit', edit_post_attach_path(@post_attach) %> |
<%= link_to 'Back', post_attaches_path %>