config/routes.rb
Rails.application.routes.draw do
  resources :post_attaches
  # For details on the DSLq available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get   '/signup', to: 'users#new'
  post  '/signup', to: 'users#create'

  get   '/signin', to: 'sessions#new'
  post  '/signin', to: 'sessions#create'

  get   '/allpost', to: 'posts#index2'
  post  '/allpost', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  # get '/search' => 'posts#search', :as => 'search_page'
  # get '/searchbypost' => 'posts#searchbypost', :as => 'searchbypost_page'
 
  # get '/search', to: 'posts#search'
  get '/searchbypost', to: 'posts#searchbypost'
  

  # except は only の逆で、指定したアクション以外の全てのアクションに適用する
  resources :users, except: [:new, :create]
  resources :posts, except: [:index]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  resources :posts
  get '/upload_photos' => 'photos#upload_photos', as: :upload_photos
  post '/upload' => 'photos#upload', as: :upload
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :posts
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :posts
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :posts
end

app/models/major.rb
class Major < ApplicationRecord
has_many :posts
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :country
  belongs_to :language
  belongs_to :stay_type
  belongs_to :kind
  belongs_to :term
  belongs_to :budget
  belongs_to :major

  validates :title, presence: true, length: { maximum: 20 }
  validates :school, presence: true
  validates :school_address, presence: true
  validates :comment_social, presence: true
  validates :comment_country, presence: true
  validates :comment_advice, presence: true
  validates :comment_school, presence: true
  mount_uploader :image, PostImageUploader
  mount_uploaders :avatars, AvatarUploader
  has_many :avatars
  accepts_nested_attributes_for :avatars
  has_many :post_attaches
   accepts_nested_attributes_for :post_attaches
  # def self.search(search)
  #   where("name LIKE ? OR country LIKE ?", "%#{search}%", "%#{search}%") 
  # end
end

app/models/post_attach.rb
class PostAttach < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sex.rb
class Sex < ApplicationRecord
    has_many :users
end

app/models/stay.rb
class Stay < ApplicationRecord
has_many :posts
end

app/models/stay_type.rb
class StayType < ApplicationRecord
  has_many :posts
end

app/models/term.rb
class Term < ApplicationRecord
has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  # userを削除したらそのuserに属するpostも削除される
  has_many :posts, dependent: :destroy

  # DM機能関係
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  # saveする前に、入力されたemailを全て小文字に変換する
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 20 }

  # 入力されたものがemailとしてふさわしいかどうかを検証する正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }}

  has_secure_password
  # users#edit でパスワードの入力を必要としないための記述
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # carrierwaveのuploaderとuser.imageを結びつけるための記述
  mount_uploader :image, UserImageUploader
  acts_as_messageable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :signed_in?, except: [:index, :show]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def index2
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post_attaches = @post.post_attaches.all
  end

  def new
    @post = Post.new
    @post_attach = @post.post_attaches.build
  end

  #def create
   # @post = Post.new(post_params)
    #if @post.save
     # redirect_to root_url
    #else
     # render 'new'
    #end
  #end

  def create
    @post = Post.new(post_params)
 
    respond_to do |format|
      # if @post.save
      #   params[:post_attaches]['avatar'].each do |a|
      #      @post_attach = @post.post_attaches.create!(:avatar => a)
      #   end
      #   format.html { redirect_to @post, notice: 'Post was successfully created.' }
      # else
      #   format.html { render action: 'new' }
      # end
      @post.save
      format.html { redirect_to @post, notice: 'Post was successfully created.' }
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_url
  end

  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = User.all.where("lower(name) LIKE :search", search: "%#{@parameter}%") 
    end  
  end 

  def searchbypost
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase
      @results = Post.joins(:country, :language, :term, :budget, :kind, :major).where("lower(countries.name) LIKE :search OR 
      lower(languages.name) LIKE :search OR lower(terms.name) LIKE :search OR lower(budgets.name) LIKE :search OR 
      lower(kinds.name) LIKE :search OR lower(majors.name) LIKE :search", search: "#{params[:search].downcase}%").uniq   
      
     
      
    end  
  end 

  def searchbycountry
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Post.all.where("lower(:country_id) LIKE :search", search: "%#{@parameter}%") 
    end  
  end 

  def upload_photos
  end
  
  def upload
      @photo = Photo.new(image: params[:file])
      parsed = Photo.parse_filename(params[:name])
      @photo.title = parsed[:title]
      if @photo.save
        head 200
      end
    end

    def self.parse_filename(filename)
      filename.gsub!(/(.jpg|.png)/, '')
      return nil unless filename =~ /^\w*-(([a-zA-Z])*(_|$))*/
      filename.split('_').join(' ')
      {title: filename}
    end
    
  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :title, 
        :image,  
        :school,
        :school_address,
        :comment_school,
        :comment_advice,
        :comment_country,
        :comment_social,
        :stay_type_id,
        :country_id,
        :language_id,
        :user_id,
        :kind_id,
        :term_id,
        :budget_id,
        :major_id,
        {avatars: []},
        post_attaches_attributes: [:id, :post_id, :avatar]
      )
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="postform">
  <%= form_with model: @post, local: true do |f| %>
    <%# エラーメッセージを表示 %>
    <%= render 'shared/error_messages', model: f.object %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="postform-tex">
      <label for="tex">
        <%= f.label :タイトル %> : </label><br>
        <div class="postform-tex_field">
        <%= f.text_field :title %></div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :国 %>: </label><br>
        <div class="sel_select">
        <%= f.collection_select :country_id, Country.all, :id, :name, prompt: "Not selected" %> </div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :言語 %>: </label><br>
       <div class="sel_select">
        <%= f.collection_select :language_id, Language.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :宿泊形態 %>: </label><br>
         <div class="sel_select">
        <%= f.collection_select :stay_type_id, StayType.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :留学種類 %>: </label><br>
         <div class="sel_select">
        <%= f.collection_select :kind_id, Kind.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :期間 %>: </label><br>
         <div class="sel_select">
        <%= f.collection_select :term_id, Term.all, :id, :name, prompt: "Not selected" %></div>
    </div>
 
 <div class="postform-tex">
      <label for="tex"><%= f.label :学校あるいは会社の名前 %>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :school %>
      </div>
    </div>

 <div class="postform-tex">
      <label for="tex"><%= f.label :学校あるいは会社の住所 %>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :school_address %>
      </div>
    </div>

  
    <div class="postform-sel">
    <label for="sel">
        <%= f.label :専攻 %>: </label><br>
         <div class="sel_select">
         <%= f.collection_select :major_id, Major.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="postform-sel">
    <label for="sel">
        <%= f.label :予算 %>:  </label><br>
         <div class="sel_select">
         <%= f.collection_select :budget_id, Budget.all, :id, :name, prompt: "Not selected" %></div>
    </div>


    <div class="postform-image">
      <label for="image" class="image_input">写真</label>
      <div class="image_field">
        <%= f.label :image %>
        <%= f.file_field :image, accept: "image/jpeg, image/jpg, image/gif, image/png", class: "input_default" %>
      </div>
    </div>


    <!--<div class="postform-image">
    <label for="image">
        <%= f.label :写真 %>: </label><br>
        <div class="input_default">
        <%= f.file_field :image, accept: "image/jpeg, image/jpg, image/gif, image/png" %></    </div>-->

       <!--<div class="postform-image">
        <label for="image" class="image_input">写真</label>
        <%= f.fields_for :post_attaches do |p| %>
          <div class="image_field">
            <%= p.label :写真 %>
            <%= p.file_field :avatar, :multiple => true, name: "post_attaches[avatar][]", class: "input_default" %>
        <% end %>
        </div>
      </div>-->
        <!--<div class="postform-image">
          <%= f.fields_for :post_attaches do |p| %>
              <%= p.label :写真 %><br>
              <%= p.file_field :avatar, :multiple => true, name: "post_attaches[avatar][]" %>
            </div>
          <% end %>
        </div>-->
        

  <%= f.fields_for :post_attaches do |p| %>
     <div class="avater">
       <%= f.label :avatar, class: "avlabel" %><br>
       <%= p.file_field :avatar, :multiple => true, name: "post_attaches[avatar][]", class: "ava_de" %>
     </div>
   <% end %>

 <div class="postform-tex">
      <label for="tex"><%= f.label :国の感想 %>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :comment_country %>
      </div>
    </div>

    <div class="postform-tex">
      <label for="tex"><%= f.label :学校あるいは会社の感想%>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :comment_school %>
      </div>
    </div>
   
  <div class="postform-tex">
      <label for="tex"><%= f.label :社会の感想%>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :comment_social %>
      </div>
    </div>

 <div class="postform-tex">
      <label for="tex"><%= f.label :自分からのアドバイス%>:</label><br>
      <div class="postform-tex_field">
      <%= f.text_field :comment_advice %>
      </div>
    </div>

    <hr class="postform-style">

    <div class="postform-button">
      <!--<%= f.submit yield(:button_text) %>-->
      <%= f.submit 'Create new post', :class=>"b" %>
    </div>

  <% end %>
  <%= link_to  "Back", :back, class: "back" %>

</div>

app/views/posts/_form2.html.erb
<div>
  <%= form_with model: @post, local: true do |f| %>
    <%# エラーメッセージを表示 %>
    <%= render 'shared/error_messages', model: f.object %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="email">
      <label for="title">
        <%= f.label :タイトル %> : </label><br>
        <div class="email_f">
        <%= f.text_field :title %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :国 %>: </label><br>
        <div class="email_f">
        <%= f.collection_select :country_id, Country.all, :id, :name, prompt: "Not selected" %> </div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :言語 %>: </label><br>
       <div class="email_f">
        <%= f.collection_select :language_id, Language.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :宿泊形態 %>: </label><br>
         <div class="email_f">
        <%= f.collection_select :stay_type_id, StayType.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :留学種類 %>:</label><br>
         <div class="email_f">
        <%= f.collection_select :kind_id, Kind.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :期間 %>: </label><br>
         <div class="email_f">
        <%= f.collection_select :term_id, Term.all, :id, :name, prompt: "Not selected" %></div>
    </div>
 
 <div class="email">
      <label for="email"><%= f.label :学校あるいは会社の名 %>:</label><br>
      <div class="email_f">
      <%= f.text_field :school %>
      </div>
    </div>

 <div class="email">
      <label for="email"><%= f.label :学校あるいは会社の住所 %>:</label><br>
      <div class="email_f">
      <%= f.text_field :school_address %>
      </div>
    </div>

  
    <div class="email">
    <label for="email">
        <%= f.label :専攻 %>: </label><br>
         <div class="email_f">
         <%= f.collection_select :major_id, Major.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :予算 %>:  </label><br>
         <div class="email_f">
         <%= f.collection_select :budget_id, Budget.all, :id, :name, prompt: "Not selected" %></div>
    </div>

    <div class="email">
    <label for="email">
        <%= f.label :Top写真 %>: </label><br>
        <div class="email_f">
        <%= f.file_field :image, accept: "image/jpeg, image/jpg, image/gif, image/png" %></    </div>

<div class="email">
    <label for="email">
        <%= f.label :他の写真 %>: </label><br>
<%= f.fields_for :post_attaches do |p| %>
     <div class="field">
       <%= p.label :Avatar %><br>
       <%= p.file_field :avatar, :multiple => true, name: "post_attaches[avatar][]" %>
     </div>
   <% end %>

 <div class="email">
      <label for="email"><%= f.label :国の感想 %>:</label><br>
      <div class="email_f">
      <%= f.text_field :comment_country %>
      </div>
    </div>

    <div class="email">
      <label for="email"><%= f.label :学校あるいは会社の感想%>:</label><br>
      <div class="email_f">
      <%= f.text_field :comment_school %>
      </div>
    </div>
   
  <div class="email">
      <label for="email"><%= f.label :社会の感想%>:</label><br>
      <div class="email_f">
      <%= f.text_field :comment_social %>
      </div>
    </div>

 <div class="email">
      <label for="email"><%= f.label :自分からのアドバイス%>:</label><br>
      <div class="email_f">
      <%= f.text_field :comment_advice %>
      </div>
    </div>


    <div>
      <%= f.submit yield(:button_text) %>
    </div>
  <% end %>

  <%= link_to  "Back", :back %>

</div>

app/views/posts/_postform.html.erb
<%
=begin%>
 <% @post.each do |post| %>  
<%
=end%>
    <%
=begin%>
#  <p>
#         <%
# =begin%>
#  <%= post.name %><br> 
# <%
# =end%>
#         <%= image_tag post.image.url %>
#         <%
# =begin%>
#  <%= post.country %><br> 
# <%
# =end%>
#     </p> 
<%
=end%>

<hr>
<%= form_for :posts, url: 'posts/create' do |t| %>
    <p><%=t.label "投稿者" %><br><%= t.text_field :name, placeholder: 'ハンドルネーム' %></p>
    <p><%=t.label "画像をアップロード" %><br><%= t.file_field :image %></p>
     <p><%=t.label "kuni" %><br><%= t.collection_select :country_id, Country.all, :id, :name %>
      <p><%=t.label "stay" %><br><%= t.collection_select :stay_id, Stay.all, :id, :name %></p>
      <p><%=t.label "kind" %><br><%= t.collection_select :kind_id, Kind.all, :id, :name %></p>
      <%
=begin%>
 <p><%=t.label "User" %><br><%= t.collection_select :user_id, User.a ll, :id, :name %></p> 
<%
=end%>
      <p><%=t.label "Language" %><br><%= t.collection_select :language_id, Language.all, :id, :name %></p>
      <p><%=t.label "Bookmark" %><br><%= t.text_field :bookmark_id, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "Like" %><br><%= t.text_field :like_id, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "Region" %><br><%= t.text_field :region, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "school" %><br><%= t.text_field :school, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "school address" %><br><%= t.text_field :school_address, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "Major" %><br><%= t.text_field :major, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "purpose" %><br><%= t.text_field :purpose, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "term" %><br><%= t.text_field :term, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "flight plan" %><br><%= t.text_field :flight_plan, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "budget" %><br><%= t.text_field :budget, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "language level" %><br><%= t.text_field :language_level, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c impression" %><br><%= t.text_field :comment_impression, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c school" %><br><%= t.text_field :comment_school, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c food" %><br><%= t.text_field :comment_food, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c stay" %><br><%= t.text_field :comment_stay, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c manner" %><br><%= t.text_field :comment_manner, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c social" %><br><%= t.text_field :comment_social, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c advice" %><br><%= t.text_field :comment_advice, placeholder: 'ハンドルネーム' %></p>
      <p><%=t.label "c accident" %><br><%= t.text_field :comment_accident, placeholder: 'ハンドルネーム' %></p>
    <p><%=t.label "c anxiety" %><br><%= t.text_field :comment_anxiety, placeholder: 'ハンドルネーム' %></p>
    <p><%=t.submit %></p>
<% end %>    
 

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<% provide(:button_text, 'Update') %>
<%= render "form2" %>

app/views/posts/index.html.erb
<!--スライダーここから-->
<div class="slideshow-container">
  <% @posts.first(6).each do |post| %>
    <div class="mySlides fade">
      <!--div class="numbertext">1 / 6</div>-->
      <div class="show-img"><%= image_tag post.image_url %></div>
      <!--<img src="ayaka1.jpg" style="width:100%">-->
    </div>
  <%end%>
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>

<br>
<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span>
  <span class="dot" onclick="currentSlide(2)"></span>
  <span class="dot" onclick="currentSlide(3)"></span>
</div>

<script>
  var slideIndex = 0;
  showSlides();

  function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    slides[slideIndex-1].style.display = "block";
    setTimeout(showSlides, 3000); // Change image every 2 seconds
    }
</script>
<!--スライダーここまで-->

<center>
  <p><span class="title"> New post </span></p>
</center>


  <!--NewPostの表示ここから-->
  <main class= container>
    <% @posts.first(6).each do |post| %>
      <div class="view view-first">
          <!--<%= image_tag post.image_url %>-->
          <!--画像にリンクじゃなくてホバー？の上からリンク飛べるようになりたいです-->
          <%= link_to image_tag(post.image_url), "/posts/#{post.id}" %>

          <div class="mask">
            <h2><%= post.title %></h2>
            <p id="name"><%= post.user.name %></p>
            <p id="during"><%= post.term.name %></p>
          </div>
      </div>
    <% end %>
  </main>
  
  <!--NewPostの表示ここまで-->

  <script src="dist/js/swiper.js"></script>
  <script>
    var swiper = new Swiper('.swiper-container', {
      loop: true,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      autoplay: {
        delay: 3000,
        disableOnInteraction: true,
      },
      pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
      },
      paginationClickable: true,
    });

  </script>
  <center>
    <!--<a href="allpost_path" class="btn">View all</a>-->
    <div class ="viewallbtn">
      <a><%= link_to 'View all', allpost_path %></a>
    </div>
  </center>
<!--
  <footer>
    <p><span class = "Amii">presented by <span class = "A">A</span>mii</span></p>
  </footer>
  -->
</body>

app/views/posts/new.html.erb
<div class="new-title">
    <p>New Post</p>
</div>
<% provide(:button_text, 'Create a new post') %>
<%= render "form" %>

app/views/posts/search.html.erb
<h3>Search Result</h3>  

<% @results.each do |result| %>  
    <div class = "searchaaa">
        <%= link_to user_path(result) do %>

        <%= image_tag result.image.url, size: '160x160' %>
            <div class = "searchname">
                <a><%= result.name  %></a>
            </div>
    </div> 
    <% end %> 
<% end %> 

app/views/posts/searchbypost.html.erb
<div class="result">
    <div class="result-title">
        Search Result by Post 
    </div>

    
    <% @results.each do |result| %> 
        <div class="resultallusers">
            <%= link_to post_path(result) do %>
                <%= image_tag result.image.url, size: '160x160' %>  
                <div class = "resultusername">
                    <a>
                    <%= result.title %>
                    </a>
                </div>
            <% end %> 
        </div>
    <% end %>
</div>   

app/views/posts/show.html.erb
<html>
  <head>
    <<meta charset="utf-8">>
    <title>ABRRY</title>
    <link rel="stylesheet" href="postpage.css">
  </head>



  <body>

    <div class="show-img">
      <%begin%>
        <%= image_tag @post.image.url %> 
      <%rescue%>  
      <%end%>
    </div>

    <div class = "content-title">
      <p class ="posttitle"><%= @post.title %></p>
      <p class = "author">by <%= @post.user.name %> </p>
      <p class = "aboutme"><a><%= link_to "About me...", @post.user %></a></p>
    </div>

    <ul id="ul_list">
      <li class = "a1"><div class = "subtitle"> | 国</div><div class = "main"><%= @post.country.name %></div></li>
      <li class = "a2"><div class = "subtitle"> | 種類</div> <div class = "main"><%= @post.kind.name %></div></li>
      <li class = "a1"><div class = "subtitle"> | 期間</div> <div class = "main"><%= @post.term.name %></div></li>
      <li class = "a2"><div class = "subtitle"> | 宿泊形態</div> <div class = "main"><%= @post.stay_type.name %></div></li>
      <li class = "a1"><div class = "subtitle"> | 学校名</div> <div class = "main"><%= @post.school %></div></li>
      <li class = "a1"><div class = "subtitle"> | 学校住所</div> <div class = "main"><%= @post.school_address %></div></li>
      <li class = "a1"><div class = "subtitle"> | 専攻</div> <div class = "main"><%= @post.major.name %></div></li>
      <li class = "a2"><div class = "subtitle"> | 言語</div> <div class = "main"><%= @post.language.name %></div></li>
      <li class = "a2"><div class = "subtitle"> | 予算</div> <div class = "main"><%= @post.budget.name %></div></li>
      <li class = "a1"><div class = "subtitle"> | 国の感想</div> <div class = "main"><%= @post.comment_country %></div></li>
      <li class = "a1"><div class = "subtitle"><!--学校・会社の--> | 感想</div> <div class = "main"><%= @post.comment_school %></div></li>
      <!-- 今のままだと、感想の名前が長すぎて改行が発生し、それが原因でレイアウト崩れが生じている。対策が必要。-->
      <li class = "a1"><div class = "subtitle"> | 社会の感想</div> <div class = "main"><%= @post.comment_social %></div></li>
      <li class = "a1"><div class = "subtitle"> | アドバイス</div> <div class = "advice"><%= @post.comment_advice %></div></li>
      <!--<li class = "a1">-->
    </ul>
    <div class = "comment">
      <%begin%>
        <!--<li class ="aaaa"><div class = "subtitle">Photo</div></li>-->
        <!--<p class = "a2"><div class = "main"><%= @post.comment %></div></p> -->
      <%rescue%>
        <!--<p class = "a2"><div class = "main" id="NoComment">NoComment</div></p>-->
      <%end%>
    </div>

    <div class="show-img">
<% @post_attaches.each do |p| %>
<%= image_tag p.avatar_url %>
<% end %>
</div>

<%
=begin%>
 <%= link_to 'edit post', edit_post_path(@post)%> 
<%
=end%>
  </body>

</html>