config/routes.rb
Rails.application.routes.draw do
  resources :post_attaches
  # For details on the DSLq available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get   '/signup', to: 'users#new'
  post  '/signup', to: 'users#create'

  get   '/signin', to: 'sessions#new'
  post  '/signin', to: 'sessions#create'

  get   '/allpost', to: 'posts#index2'
  post  '/allpost', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  # get '/search' => 'posts#search', :as => 'search_page'
  # get '/searchbypost' => 'posts#searchbypost', :as => 'searchbypost_page'
 
  # get '/search', to: 'posts#search'
  get '/searchbypost', to: 'posts#searchbypost'
  

  # except は only の逆で、指定したアクション以外の全てのアクションに適用する
  resources :users, except: [:new, :create]
  resources :posts, except: [:index]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  resources :posts
  get '/upload_photos' => 'photos#upload_photos', as: :upload_photos
  post '/upload' => 'photos#upload', as: :upload
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :posts
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :posts
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :posts
end

app/models/major.rb
class Major < ApplicationRecord
has_many :posts
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :country
  belongs_to :language
  belongs_to :stay_type
  belongs_to :kind
  belongs_to :term
  belongs_to :budget
  belongs_to :major

  validates :title, presence: true, length: { maximum: 20 }
  validates :school, presence: true
  validates :school_address, presence: true
  validates :comment_social, presence: true
  validates :comment_country, presence: true
  validates :comment_advice, presence: true
  validates :comment_school, presence: true
  mount_uploader :image, PostImageUploader
  mount_uploaders :avatars, AvatarUploader
  has_many :avatars
  accepts_nested_attributes_for :avatars
  has_many :post_attaches
   accepts_nested_attributes_for :post_attaches
  # def self.search(search)
  #   where("name LIKE ? OR country LIKE ?", "%#{search}%", "%#{search}%") 
  # end
end

app/models/post_attach.rb
class PostAttach < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sex.rb
class Sex < ApplicationRecord
    has_many :users
end

app/models/stay.rb
class Stay < ApplicationRecord
has_many :posts
end

app/models/stay_type.rb
class StayType < ApplicationRecord
  has_many :posts
end

app/models/term.rb
class Term < ApplicationRecord
has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  # userを削除したらそのuserに属するpostも削除される
  has_many :posts, dependent: :destroy

  # DM機能関係
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  # saveする前に、入力されたemailを全て小文字に変換する
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 20 }

  # 入力されたものがemailとしてふさわしいかどうかを検証する正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }}

  has_secure_password
  # users#edit でパスワードの入力を必要としないための記述
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # carrierwaveのuploaderとuser.imageを結びつけるための記述
  mount_uploader :image, UserImageUploader
  acts_as_messageable
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="email_f">
  <strong><%= link_to "ABRRY", root_url %></strong>
  <% if current_user %>
    <%= link_to  'My page', user_path(current_user) %>
  <% else %>
    <%= link_to "Sign up", signup_path %>
  <% end %>
  <%= link_to  "All Users", users_path %>
  <%= link_to  "New post", new_post_path %>

  <%= form_tag(searchbypost_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <div class="email_f"><%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %></div>  
    <div class="input-group-btn">  
      <%= button_tag "Search by user", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>

   <%= form_tag(searchbypost_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Search by post", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div> 

<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>